# Generated by Django 5.1.1 on 2024-09-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='max_grade',
        ),
    ]
