# Generated by Django 5.1.1 on 2024-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_questionset_max_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
